export type SeoPage = {
  title: string;
  description: string;
  path: string;
  focusKeyword: string;
  secondaryKeywords: string[];
  schemaTypes: string[];
};

const page = (
  title: string,
  description: string,
  path: string,
  focusKeyword: string,
  secondaryKeywords: string,
  schemaTypes: string[],
): SeoPage => ({
  title,
  description,
  path,
  focusKeyword,
  secondaryKeywords: secondaryKeywords.split("; "),
  schemaTypes,
});

export const seoPages: Record<string, SeoPage> = {
  "/": page("Dr. Sanjay Sonar | Advanced Laparoscopic Surgeon in Mumbai", "Consult Dr. Sanjay Sonar, an advanced laparoscopic surgeon in Mumbai with 35+ years of experience in complex and minimally invasive surgery.", "/", "advanced laparoscopic surgeon in Mumbai", "laparoscopic surgeon Mumbai; general surgeon Mumbai; GI surgeon Mumbai; minimally invasive surgeon Mumbai; Dr. Sanjay Sonar", ["Physician", "MedicalBusiness"]),
  "/about": page("Dr. Sanjay Sonar | Laparoscopic Surgeon in Mumbai", "Learn about Dr. Sanjay Sonar, an experienced laparoscopic surgeon in Mumbai with over 35 years of surgical experience and academic expertise.", "/about", "Dr. Sanjay Sonar", "laparoscopic surgeon Mumbai; advanced laparoscopic surgeon; general surgeon Mumbai; experienced surgeon Mumbai; GI surgeon Mumbai", ["Physician", "MedicalBusiness"]),
  "/expertise": page("Surgical Expertise | Dr. Sanjay Sonar, Mumbai", "Explore Dr. Sanjay Sonar's expertise in advanced laparoscopic, gastrointestinal, hernia, colorectal and minimally invasive surgery in Mumbai.", "/expertise", "laparoscopic surgery in Mumbai", "advanced laparoscopic surgery Mumbai; GI surgery Mumbai; hernia surgery Mumbai; colorectal surgery Mumbai; minimally invasive surgery Mumbai", ["Physician", "MedicalBusiness"]),
  "/teaching": page("Surgical Teaching & Training | Dr. Sanjay Sonar", "Explore Dr. Sanjay Sonar's contribution to surgical teaching, advanced laparoscopic training, workshops and academic education in India and abroad.", "/teaching", "laparoscopic surgery training", "advanced laparoscopic surgery training; laparoscopic surgery workshops; surgical training Mumbai; laparoscopic surgeon educator; surgical workshops India", ["Physician", "EducationalOrganization"]),
  "/gallery": page("Surgical Gallery | Dr. Sanjay Sonar, Mumbai", "View highlights from Dr. Sanjay Sonar's surgical practice, teaching sessions, workshops, academic activities and professional work.", "/gallery", "Dr. Sanjay Sonar", "laparoscopic surgeon Mumbai; laparoscopic surgery; surgical workshops; surgical training; minimally invasive surgery", ["Physician", "ImageGallery"]),
  "/selected-work": page("Surgical Cases & Selected Work | Dr. Sanjay Sonar", "Explore selected surgical cases and complex procedures performed by Dr. Sanjay Sonar, an experienced laparoscopic surgeon in Mumbai.", "/selected-work", "complex surgery in Mumbai", "complex laparoscopic surgery Mumbai; advanced laparoscopic surgeon Mumbai; difficult surgical cases; laparoscopic surgery Mumbai; surgical case studies", ["Physician", "MedicalWebPage"]),
  "/consultation": page("Consult a Laparoscopic Surgeon in Mumbai | Dr. Sonar", "Book a consultation with Dr. Sanjay Sonar for advanced laparoscopic, GI, hernia, colorectal and minimally invasive surgical care in Mumbai.", "/consultation", "laparoscopic surgeon consultation Mumbai", "consult laparoscopic surgeon Mumbai; surgeon consultation Mumbai; GI surgeon consultation; hernia surgeon consultation; surgical second opinion Mumbai", ["Physician", "MedicalBusiness"]),
  "/site-map": page("Site Map | Dr. Sanjay Sonar", "Browse the Dr. Sanjay Sonar website, including surgical expertise, teaching, selected work and consultation pages.", "/site-map", "Dr. Sanjay Sonar site map", "surgical expertise; laparoscopic surgeon Mumbai; consultation", ["MedicalWebPage"]),
  "/expertise/laparoscopic-hellers-cardiomyotomy": page("Laparoscopic Heller's Cardiomyotomy in Mumbai | Dr. Sonar", "Learn about laparoscopic Heller's cardiomyotomy for achalasia, including how the procedure works, who may need it and what recovery involves.", "/expertise/laparoscopic-hellers-cardiomyotomy", "Heller's cardiomyotomy Mumbai", "laparoscopic Heller's cardiomyotomy; achalasia surgery Mumbai; achalasia surgeon Mumbai; Heller myotomy Mumbai; achalasia treatment Mumbai", ["MedicalProcedure", "Physician"]),
  "/expertise/laparoscopic-hiatus-hernia-surgery": page("Hiatus Hernia Surgery in Mumbai | Dr. Sanjay Sonar", "Learn about laparoscopic hiatus hernia surgery, including when surgery may be needed, how it is performed and what recovery involves.", "/expertise/laparoscopic-hiatus-hernia-surgery", "hiatus hernia surgery Mumbai", "laparoscopic hiatus hernia surgery; hiatus hernia surgeon Mumbai; hiatus hernia treatment Mumbai; laparoscopic hernia surgery Mumbai; hiatal hernia surgery Mumbai", ["MedicalProcedure", "Physician"]),
  "/expertise/complex-hernia-surgery": page("Complex Hernia Surgery in Mumbai | Dr. Sanjay Sonar", "Explore complex hernia surgery in Mumbai, including treatment approaches for large, recurrent and difficult abdominal wall hernias.", "/expertise/complex-hernia-surgery", "complex hernia surgery Mumbai", "complex hernia surgeon Mumbai; complex hernia repair Mumbai; difficult hernia surgery; abdominal wall reconstruction Mumbai; advanced hernia surgery Mumbai", ["MedicalProcedure", "Physician"]),
  "/expertise/laparoscopic-rectopexy": page("Laparoscopic Rectopexy in Mumbai | Dr. Sanjay Sonar", "Learn about laparoscopic rectopexy for rectal prolapse, including the procedure, who may need surgery and what recovery involves.", "/expertise/laparoscopic-rectopexy", "laparoscopic rectopexy Mumbai", "rectal prolapse surgery Mumbai; rectopexy surgeon Mumbai; rectal prolapse treatment Mumbai; laparoscopic rectal prolapse surgery; colorectal surgeon Mumbai", ["MedicalProcedure", "Physician"]),
  "/expertise/laparoscopic-colectomy": page("Laparoscopic Colectomy in Mumbai | Dr. Sanjay Sonar", "Learn about laparoscopic colectomy, a minimally invasive procedure to remove part of the colon for selected colorectal conditions.", "/expertise/laparoscopic-colectomy", "laparoscopic colectomy Mumbai", "colectomy surgeon Mumbai; colorectal surgeon Mumbai; laparoscopic colorectal surgery Mumbai; colon surgery Mumbai; colorectal surgery Mumbai", ["MedicalProcedure", "Physician"]),
  "/expertise/advanced-gi-surgery": page("Advanced GI Surgeon in Mumbai | Dr. Sanjay Sonar", "Dr. Sanjay Sonar provides advanced gastrointestinal and laparoscopic surgery in Mumbai for a range of complex digestive conditions.", "/expertise/advanced-gi-surgery", "GI surgeon Mumbai", "gastrointestinal surgeon Mumbai; advanced GI surgery Mumbai; laparoscopic GI surgeon Mumbai; GI surgery Mumbai; gastrointestinal surgery Mumbai", ["Physician", "MedicalProcedure"]),
  "/expertise/laparoscopic-cholecystectomy": page("Laparoscopic Gallbladder Surgery in Mumbai | Dr. Sonar", "Learn about laparoscopic gallbladder removal surgery, including when it is recommended, how it is performed and what recovery involves.", "/expertise/laparoscopic-cholecystectomy", "laparoscopic gallbladder surgery Mumbai", "laparoscopic cholecystectomy Mumbai; gallbladder surgeon Mumbai; gallstone surgery Mumbai; gallbladder stone treatment Mumbai; gallbladder removal Mumbai", ["MedicalProcedure", "Physician"]),
  "/expertise/laparoscopic-thyroid-surgery": page("Thyroid Surgery in Mumbai | Dr. Sanjay Sonar", "Learn about thyroid surgery, including laparoscopic approaches, when surgery may be recommended and what patients can expect.", "/expertise/laparoscopic-thyroid-surgery", "thyroid surgeon Mumbai", "thyroid surgery Mumbai; laparoscopic thyroid surgery Mumbai; thyroidectomy Mumbai; thyroid surgeon South Mumbai; thyroid treatment Mumbai", ["MedicalProcedure", "Physician"]),
  "/expertise/laparoscopic-pyeloplasty": page("Laparoscopic Pyeloplasty in Mumbai | Dr. Sanjay Sonar", "Learn about laparoscopic pyeloplasty, a minimally invasive procedure used to treat blockage at the junction between the kidney and ureter.", "/expertise/laparoscopic-pyeloplasty", "laparoscopic pyeloplasty Mumbai", "pyeloplasty surgeon Mumbai; pyeloplasty Mumbai; laparoscopic urological surgery Mumbai; UPJ obstruction surgery Mumbai; kidney surgery Mumbai", ["MedicalProcedure", "Physician"]),
  "/expertise/laser-treatment-varicose-veins": page("Laser Varicose Vein Treatment in Mumbai | Dr. Sonar", "Learn about laser treatment for varicose veins, including how the minimally invasive procedure works, its benefits and recovery.", "/expertise/laser-treatment-varicose-veins", "laser varicose vein treatment Mumbai", "varicose vein treatment Mumbai; varicose vein surgeon Mumbai; laser treatment for varicose veins; varicose veins surgery Mumbai; minimally invasive vein treatment Mumbai", ["MedicalProcedure", "Physician"]),
  "/expertise/thoracic-surgery": page("Thoracic Surgeon in Mumbai | Dr. Sanjay Sonar", "Explore Dr. Sanjay Sonar's expertise in thoracic surgery and minimally invasive surgical treatment for selected chest and lung conditions.", "/expertise/thoracic-surgery", "thoracic surgeon Mumbai", "thoracic surgery Mumbai; chest surgeon Mumbai; lung surgeon Mumbai; minimally invasive thoracic surgery Mumbai; thoracic surgery specialist Mumbai", ["Physician", "MedicalProcedure"]),
  "/expertise/urological-surgery": page("Urological Surgeon in Mumbai | Dr. Sanjay Sonar", "Explore Dr. Sanjay Sonar's expertise in minimally invasive urological surgery, including laparoscopic procedures for selected urinary conditions.", "/expertise/urological-surgery", "urological surgeon Mumbai", "urological surgery Mumbai; laparoscopic urological surgery Mumbai; minimally invasive urological surgery; urinary surgery Mumbai; urology surgeon Mumbai", ["Physician", "MedicalProcedure"]),
  "/expertise/colorectal-surgery": page("Colorectal Surgeon in Mumbai | Dr. Sanjay Sonar", "Dr. Sanjay Sonar offers colorectal surgical care in Mumbai, including minimally invasive procedures for selected colorectal conditions.", "/expertise/colorectal-surgery", "colorectal surgeon Mumbai", "colorectal surgery Mumbai; laparoscopic colorectal surgery Mumbai; colon surgeon Mumbai; rectal surgery Mumbai; colorectal specialist Mumbai", ["Physician", "MedicalProcedure"]),
  "/expertise/laparoscopic-surgery": page("Laparoscopic Surgeon in Mumbai | Dr. Sanjay Sonar", "Explore minimally invasive laparoscopic surgery by Dr. Sanjay Sonar for selected abdominal and gastrointestinal conditions in Mumbai.", "/expertise/laparoscopic-surgery", "laparoscopic surgeon Mumbai", "laparoscopic surgery Mumbai; advanced laparoscopic surgeon Mumbai; minimally invasive surgery Mumbai; laparoscopic surgeon South Mumbai; abdominal laparoscopic surgery Mumbai", ["Physician", "MedicalProcedure"]),
  "/expertise/hernia-surgery": page("Hernia Surgeon in Mumbai | Laparoscopic Hernia Surgery", "Learn about laparoscopic and advanced hernia surgery in Mumbai, including treatment options for different types of abdominal and groin hernias.", "/expertise/hernia-surgery", "hernia surgeon Mumbai", "hernia surgery Mumbai; laparoscopic hernia surgery Mumbai; laparoscopic hernia surgeon Mumbai; hernia treatment Mumbai; abdominal hernia surgery Mumbai", ["Physician", "MedicalProcedure"]),
};

export const seoPageList = Object.values(seoPages);

export function getSeoPage(path: string): SeoPage | undefined {
  const normalized = path === "/" ? "/" : path.replace(/\/$/, "");
  return seoPages[normalized];
}
